image: "maven"

stages:
  - build
  - test
  - quality
  - build_candidate

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - complete/.m2/
    - complete/target/

before_script:
  - cd complete

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test
    - mvn jacoco:report
  artifacts:
    reports:
      junit: complete/target/surefire-reports/*.xml

quality:
  stage: quality
  script:
    - mvn sonar:sonar

package:
  stage: build_candidate
  script:
    - mvn -DskipTests package
  artifacts:
    paths:
      - complete/target/*.jar

tag:
  stage: build_candidate
  script:
    - echo "git tag $(date -I)BC"