name: Java CI

on:
  push:
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1.1.0
      with:
        path: complete/target/
        key: ${{ GITHUB_SHA }}
    - name: Build with Maven
      working-directory: complete/
      run:  mvn -B compile
  
  
  unit_test:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1.1.0
      with:
        path: complete/target/
        key: ${{ GITHUB_SHA }}
    - name: Unit test
      working-directory: complete/
      run: mvn -B test
    - name: Generate code coverage report
      working-directory: complete/
      run: mvn -B jacoco:report
      

  code_quality:
    needs: [unit_test]
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1.1.0
      with:
        path: complete/target/
        key: ${{ GITHUB_SHA }}
    - name: Code Quality
      run: mvn -B sonar:sonar
      working-directory: complete/
